# Generated by Django 5.2.4 on 2025-08-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedAudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_file",
                    models.FileField(upload_to="processed_audio_files/"),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.audiofile"
                    ),
                ),
            ],
        ),
    ]
