# Generated by Django 5.2.4 on 2025-08-12 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_processedaudiofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.audiofile"
                    ),
                ),
            ],
        ),
    ]
