# Generated by Django 5.2.4 on 2025-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_subscriptionplan_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
